Feature/py39
bitwarden/passwordless-python pull request #73
Opened 2024-09-17 12:36 UTC by jonashendrickx

### Ticket

- Closes [PAS-XXX](https://bitwarden.atlassian.net/browse/PAS-XXX)

### Description

### Shape

### Screenshots

### Checklist
I did the following to ensure that my changes were tested thoroughly:
- __

I did the following to ensure that my changes do not introduce security vulnerabilities:
- __

2024-09-17 13:49 UTC, mzieniukbw requested changes
Looks good, but missing GH CD workflow and readme updates

2024-09-17 13:49 UTC, mzieniukbw commented on examples/streamlit/pyproject.toml
>  passwordless = "^1"
```suggestion
passwordless = "^2"
```

2024-09-17 13:49 UTC, mzieniukbw commented on examples/flask/pyproject.toml
>  passwordless = "^1"
```suggestion
passwordless = "^2"
```

2024-09-17 13:49 UTC, mzieniukbw commented on .github/workflows/ci.yml
>          run: poetry install --with dev,test
I am not sure if this is actually using python 3.9. I have only learned recently that the ubuntu-latest GH image already have python installed and poetry will use that one as default and not 3.9.
I would advise adding a step before the `Build`: `poetry env info`.
To fix this, i think we need `poetry env use 3.9`

2024-09-17 13:49 UTC, mzieniukbw commented on examples/flask/pyproject.toml
💡 how about we add a GH CI workflow (or use existing) for both examples ? At least run `poetry install --with dev` to see if it dependencies are ok.
Note: To use PR's `passwordless` dependency, you might need `poetry install --directory ../..`

2024-09-17 13:49 UTC, mzieniukbw commented on examples/flask/pyproject.toml
Update README

2024-09-17 13:49 UTC, mzieniukbw commented on examples/streamlit/pyproject.toml
Update README

2024-09-17 13:49 UTC, mzieniukbw commented on .github/workflows/ci.yml
`cd.yml` workflow also uses python 3.9. It might also be missing the `poetry env use 3.9` i mentioned here

2024-09-18 09:27 UTC, mzieniukbw commented on .github/workflows/ci.yml
> +          cd examples/flask;
⛏️ 
```suggestion
          cd examples/flask
```

2024-09-18 09:27 UTC, mzieniukbw commented on .github/workflows/ci.yml
> +          poetry install --with dev
new line missing

2024-09-18 09:27 UTC, mzieniukbw commented on .github/workflows/ci.yml
> +          cd examples/streamlit;
```suggestion
          cd examples/streamlit
```

2024-09-18 11:44 UTC, mzieniukbw approved these changes
LGTM

2024-09-24 14:26 UTC, abergs approved these changes

2024-09-24 14:31 UTC, merged